models/Personajes.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "personajes".
 *
 * @property int $cod
 * @property string|null $nombre
 * @property string|null $autor
 * @property int|null $nivel
 * @property string|null $clase
 * @property string|null $cod_partidas
 * @property string|null $nom_clase
 * @property string|null $nom_elemento
 * @property string|null $nom_zona
 * @property int|null $muerto
 *
 * @property Partidas[] $partidas
 * @property Partidas[] $partidas0
 * @property Clases $nomClase
 * @property Elementos $nomElemento
 * @property Zonas $nomZona
 */
class Personajes extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'personajes';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nivel', 'muerto'], 'integer'],
            [['nivel'],'default','value'=>'5'],
            [['muerto'],'default','value'=>'0'],
            [['nombre', 'autor', 'nom_clase', 'nom_elemento', 'nom_zona'], 'required'],
            [['nombre'], 'string', 'max' => 10],
            [['autor',  'clase'], 'string', 'max' => 15],
            [['cod_partidas'], 'string', 'max' => 9],
            [['nom_clase', 'nom_elemento', 'nom_zona'], 'string', 'max' => 20],
            [['nom_clase'], 'exist', 'skipOnError' => true, 'targetClass' => Clases::className(), 'targetAttribute' => ['nom_clase' => 'nombre']],
            [['nom_elemento'], 'exist', 'skipOnError' => true, 'targetClass' => Elementos::className(), 'targetAttribute' => ['nom_elemento' => 'nombre']],
            [['nom_zona'], 'exist', 'skipOnError' => true, 'targetClass' => Zonas::className(), 'targetAttribute' => ['nom_zona' => 'nombre']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'cod' => 'Cod',
            'nombre' => 'Nombre',
            'autor' => 'Autor',
            'nivel' => 'Nivel',
            'clase' => 'Clase',
            'cod_partidas' => 'Cod Partidas',
            'nom_clase' => 'Nom Clase',
            'nom_elemento' => 'Nom Elemento',
            'nom_zona' => 'Nom Zona',
            'muerto' => 'Muerto',
        ];
    }

    /**
     * Gets query for [[Partidas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPartidas()
    {
        return $this->hasMany(Partidas::className(), ['cod_jugador1' => 'cod']);
    }

    /**
     * Gets query for [[Partidas0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPartidas0()
    {
        return $this->hasMany(Partidas::className(), ['cod_jugador2' => 'cod']);
    }

    /**
     * Gets query for [[NomClase]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNomClase()
    {
        return $this->hasOne(Clases::className(), ['nombre' => 'nom_clase']);
    }

    /**
     * Gets query for [[NomElemento]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNomElemento()
    {
        return $this->hasOne(Elementos::className(), ['nombre' => 'nom_elemento']);
    }

    /**
     * Gets query for [[NomZona]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNomZona()
    {
        return $this->hasOne(Zonas::className(), ['nombre' => 'nom_zona']);
    }
    
    public function actionSelecttipo($id)
    {
        if ($id == 'Arquero')
        {
            return "/imgs/weapons/class/Arquero.png";
        }
        if ($id == 'Guerrero')
        {
            return "/imgs/weapons/class/Guerrero.png";
        }
        if ($id == 'Mago')
        {
            return "/imgs/weapons/class/Mago.png";
        }
    }
    public function actionSelecttipofuerte($id)
    {
        if ($id == 'Arquero')
        {
            return "/imgs/weapons/class/Mago.png";
        }
        if ($id == 'Guerrero')
        {
            return "/imgs/weapons/class/Arquero.png";
        }
        if ($id == 'Mago')
        {
            return "/imgs/weapons/class/Guerrero.png";
        }
    }
    public function actionSelecttipodebil($id)
    {
        if ($id == 'Arquero')
        {
            return "/imgs/weapons/class/Guerrero.png";
        }
        if ($id == 'Guerrero')
        {
            return "/imgs/weapons/class/Mago.png";
        }
        if ($id == 'Mago')
        {
            return "/imgs/weapons/class/Arquero.png";
        }
    }
    
    public function actionSelectelement($id)
    {
        if ($id == 'Fuego')
        {
            return "/imgs/weapons/element/Fuego.png";
        }
        if ($id == 'Agua')
        {
            return "/imgs/weapons/element/Agua.png";
        }
        if ($id == 'Tierra')
        {
            return "/imgs/weapons/element/Tierra.png";
        }
         if ($id == 'Viento')
        {
            return "/imgs/weapons/element/Viento.png";
        }
    }
    public function actionSelectelementfuerte($id)
    {
        if ($id == 'Fuego')
        {
            return "/imgs/weapons/element/Tierra.png";
        }
        if ($id == 'Agua')
        {
            return "/imgs/weapons/element/Fuego.png";
        }
        if ($id == 'Tierra')
        {
            return "/imgs/weapons/element/Viento.png";
        }
         if ($id == 'Viento')
        {
            return "/imgs/weapons/element/Agua.png";
        }
    }
    public function actionSelectelementdebil($id)
    {
        if ($id == 'Fuego')
        {
            return "/imgs/weapons/element/Agua.png";
        }
        if ($id == 'Agua')
        {
            return "/imgs/weapons/element/Viento.png";
        }
        if ($id == 'Tierra')
        {
            return "/imgs/weapons/element/Fuego.png";
        }
         if ($id == 'Viento')
        {
            return "/imgs/weapons/element/Tierra.png";
        }
    }
    
    public function actionSelectclase($id)
    {
        switch ($id)
        {
        case ('Herrero'):
            $imgpath = "/imgs/chars/Guerrero/Fuego.png";
            break;
        case ('Caza-Dragones'):
            $imgpath = "/imgs/chars/Arquero/Fuego.jpg";
            break;
        case ('Incendiario'):
            $imgpath = "/imgs/chars/Mago/Fuego.jpg";
            break;
        case ('Pirata'):
            $imgpath = "/imgs/chars/Guerrero/Agua.jpg";
            break;
        case ('Avalanchero'):
            $imgpath = "/imgs/chars/Arquero/Agua.jpg";
            break;
        case ('Aguacante'):
            $imgpath = "/imgs/chars/Mago/Agua.jpg";
            break;
        case ('Mercenario'):
            $imgpath = "/imgs/chars/Guerrero/Tierra.png";
            break;
        case ('Cazador'):
            $imgpath = "/imgs/chars/Arquero/Tierra.png";
            break;
        case ('Djinn'):
            $imgpath = "/imgs/chars/Mago/Tierra.jpg";
            break;
        case ('Caballuco'):
            $imgpath = "/imgs/chars/Guerrero/Viento.png";
            break;
        case ('Ronin'):
            $imgpath = "/imgs/chars/Arquero/Viento.png";
            break;
        case ('Tormentador'):
            $imgpath = "/imgs/chars/Mago/Viento.jpg";
            break;
        }
        return $imgpath;
    }
    
    public function actionSelectzona($id)
    {    
        switch ($id)
        {
            case ("Desierto"):
                $imgpath = "/imgs/zones/wasteland.png";
                break;
            case ("Montaña"):
                $imgpath = "/imgs/zones/mountain.jpg";
                break;
            case ("Cueva"):
                $imgpath = "/imgs/zones/cave.jpg";
                break;
            case ("Bosque"):
                $imgpath = "/imgs/zones/forest.png";
                break;
        }
        return $imgpath;
    }
}

controllers/PersonajesController.php
<?php

//EN PERSONAJESCONTROLLER ESTA VIRTUALMENTE TODA LA FUNCIONALIDAD QUE HE CREADO, AQUI PODRAS VER TODAS LAS FUNCIONES CREADAS

namespace app\controllers;

use Yii;
use app\models\Personajes;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;

use app\models\Clases;
use app\models\Zonas;
use app\models\Elementos;
use \app\models\Partidas;
use yii\db\Query;

/**
 * PersonajesController implements the CRUD actions for Personajes model.
 */
class PersonajesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Personajes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Personajes::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Personajes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    
       /*
    /**
     * Creates a new Personajes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Personajes();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Personajes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Personajes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Personajes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Personajes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Personajes::findOne($id)) !== null) {
            return $model;
        }

        return null;
    }
    
    //MOSTRAR TODOS LOS PERSONAJES
        public function actionPersonajes()
    {     
        //buscar todos los personajes que esten vivos
        $dataProvider = new ActiveDataProvider([
            'query' => Personajes::find()->where(['muerto' => 0]),
        ]);
        
        return $this->render('personajes', [
            'dataProvider' => $dataProvider,
        ]);
    }
    //MOSTRAR TODOS LOS PERSONAJES
        public function actionEstadisticas($id)
    {
        $mymodel = $this->findModel($id);
        $imgpath = $this->actionSelectclase($mymodel->clase);
        
        //IMAGENES PARA LOS ELEMENTOS
        $imgpathElement = $this->actionSelectelement($mymodel->nom_elemento);
        $imgpathElementdebil = $this->actionSelectelementdebil($mymodel->nom_elemento);
        $imgpathElementfuerte = $this->actionSelectelementfuerte($mymodel->nom_elemento);
        
        //IMAGENES PARA LOS TIPOS
        $imgpathClass = $this->actionSelecttipo($mymodel->nom_clase);
        $imgpathClassdebil = $this->actionSelecttipodebil($mymodel->nom_clase);
        $imgpathClassfuerte = $this->actionSelecttipofuerte($mymodel->nom_clase);
        
        //IMAGENES PARA LAS ZONAS
        $imgpathZona = $this->actionSelectzona($mymodel->nom_zona);
        $imgpathZonadebil = $this->actionSelectzonadebil($mymodel->nom_zona);
        
        
        //DATA PROVIDER DE HISTORIAL DE COMBATES
        $dataProvider = new ActiveDataProvider([
            'query' => Partidas::find()
                    ->alias('p')
                    ->innerJoinWith('codjugador1','(personajes.cod = p.cod_jugador1 OR personajes.cod = p.cod_jugador2)')->alias('p1')
                    ->innerJoinWith('codjugador2', '(p1.cod = p.cod_jugador1 AND personajes.cod = p.cod_jugador2 OR p1.cod = p.cod_jugador2 AND personajes.cod = p.cod_jugador1)')
                    ->where(['cod_jugador1' => $mymodel->cod])->orderBy(['p1.cod' => SORT_DESC])->limit(5),
             'pagination' => false,
        ]);
        
        //LA CANTIDAD DE VICTORIAS OBTENIDAS POR ESTE PERSONAJE
        $victorias = new ActiveDataProvider([
            'query' => Partidas::find()->where(['ganador' => $mymodel->cod])
                ]);
        $victories = (int) $victorias->count;
        
        //LA CANTIDAD DE ENEMIGOS MATADOS POR ESTE PERSONAJE
        $matanzas = new ActiveDataProvider([
            'query' => Partidas::find()->where(['ganador' => $mymodel->cod])
                       ->andWhere(['matanza' => 1])
                ]);
        $kills = (int) $matanzas->count;
        
        //LA CANTIDAD DE PARTIDAS PERDIDAS POR ESTE PERSONAJE
        $perdidas = new ActiveDataProvider([
            'query' => Partidas::find()
                ->where("ganador != $mymodel->cod")->andWhere(['cod_jugador1' => $mymodel->cod])
                ->orWhere(['cod_jugador2' => $mymodel->cod])->andWhere("ganador != $mymodel->cod")
                ]);
        $defeats =  (int) $perdidas->count;
        
        //EL WINRATE (PORCENTAJE DE VICTORIAS)
        $countgames = $defeats + $victories;
        if ($countgames != 0)
        {
        $calcWr = $victories / ($countgames) * 100;
        $winrate = number_format($calcWr, 2);
        }
        else
        {
            $winrate = 0;
        }     
        
        //EL PERSONAJE QUE MAS TE HA VENCIDO EN COMBATES
        $nemesis = "";
        $findnemesis = new ActiveDataProvider([
           'query' => Partidas::find()->select('ganador')
                ->where("ganador != $mymodel->cod")->andWhere(['cod_jugador1' => $mymodel->cod])
                ->orWhere(['cod_jugador2' => $mymodel->cod])->andWhere("ganador != $mymodel->cod")
                ->groupBy('ganador')->orderBy('COUNT(ganador)')->limit(1)
        ]);
        $newQuery = clone $findnemesis->query;
        $cloneres = $newQuery->limit(1)->one();
        if ($cloneres)
        $nemesis = $this->findModel($cloneres->ganador)->nombre;
        
        //EL PERSONAJE QUE MAS HAS VENCIDO TU EN COMBATE
        $victima = "";
        $findvictima = new ActiveDataProvider([
           'query' => Partidas::find()->select('perdedor')
                ->where("perdedor != $mymodel->cod")->andWhere(['cod_jugador1' => $mymodel->cod])
                ->orWhere(['cod_jugador2' => $mymodel->cod])->andWhere("perdedor != $mymodel->cod")
                ->groupBy('perdedor')->orderBy('COUNT(perdedor)')->limit(1)
        ]);
        $newQuery2 = clone $findvictima->query;
        $cloneres2 = $newQuery2->limit(1)->one();
        if ($cloneres2)
        $victima = $this->findModel($cloneres2->perdedor)->nombre;
        
        //RENDERIZAR Y PASAR TODOS LOS VARIABLES RELEVANTES
        return $this->render('estadisticas', [
            'mymodel' =>$mymodel,
            'victories' =>$victories,
            'kills' =>$kills,
            'defeats' =>$defeats,
            'winrate' =>$winrate,
            'nemesis' =>$nemesis,
            'victima' =>$victima,
            'dataProvider' => $dataProvider,
            'imgpath' => $imgpath,
            'imgpathElement' => $imgpathElement,
            'imgpathElementdebil' => $imgpathElementdebil,
            'imgpathElementfuerte' => $imgpathElementfuerte,
            'imgpathClass' => $imgpathClass,
            'imgpathClassdebil' => $imgpathClassdebil,
            'imgpathClassfuerte' => $imgpathClassfuerte,
            'imgpathZona' => $imgpathZona,
            'imgpathZonadebil' => $imgpathZonadebil,
        ]);
    }
    
    
        //MOSTRAR TODOS LOS MUERTOS
        public function actionCementerio()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Personajes::find()->where(['muerto' => 1]),
        ]);
        
        return $this->render('cementerio', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
    //MOSTRAR PERSONAJE CREADO
        public function actionPersonajesingular($id)
    {
        $model = $this->findModel($id);
        $imgpath = $this->actionSelectclase($model->clase);
        
        $imgpathElement = $this->actionSelectelement($model->nom_elemento);
        $imgpathElementdebil = $this->actionSelectelementdebil($model->nom_elemento);
        $imgpathElementfuerte = $this->actionSelectelementfuerte($model->nom_elemento);
        
        $imgpathClass = $this->actionSelecttipo($model->nom_clase);
        $imgpathClassdebil = $this->actionSelecttipodebil($model->nom_clase);

views/personajes/estadisticas.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

//VIEW DE LAS ESTADISTICAS DE UN PERSONAJE

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\widgets\ListView;
use yii\grid\GridView;


$this->title = 'Crear Personaje';
$url = Yii::getAlias("@web") . '/imgs/others/';
?>

<style>    
  body {
    background:url(<?= $url ?>bg1.png);
    background-attachment: fixed;
    background-size: cover;
        font-family: 'teen', serif;
}  
.wrapper
{
        outline-style: solid;
        outline-width: 4px;
        outline-color: #0A141B;
        background-color:#0F1F2A;
        width: 900px;
        height: 400px;
        position: relative;
        left: 60px;
}
.leftpane {
    width: 20%;
    height: 51%;
    float: left;
    border-collapse: collapse;
    border-bottom: 4px solid;
    border-color:  #0A141B;
}
.leftpanebottom {
    width: 25%;
    height: 32.5%;
    float: left;
    border-collapse: collapse;
    border-bottom: 4px solid;
    border-right: 4px solid;
    border-color:  #0A141B;
}

.leftpanebottomextra {
    width: 25%;
    height: 17.5%;
    float: left;
    border-collapse: collapse;
        border-right: 4px solid;
    border-color:  #0A141B;
}

.rightpanebottom {
    width: 75%;
    height: 50%;
    float: right;
    border-collapse: collapse;
}

.middlepane {
    width: 50%;
    height: 51%;
    border-collapse: collapse;
    border-bottom: 4px solid;
    border-right: 4px solid;
    border-color:  #0A141B;
}

.rightpane {
  width: 50%;
  height: 51%;
  float: right;
  border-collapse: collapse;
    border-collapse: collapse;
    border-bottom: 4px solid;
    border-color:  #0A141B;

}

.textcolor
{
  color:#fa9632;
}

.textcolor em
{
  color:#fff3b8;
}

.textcolorG
{
  color: greenyellow;
}
.textcolorG em
{
  color:#fff3b8;
}

.textcolorR
{
  color: red;
}
.textcolorR em
{
  color:#fff3b8;
}

.imgleft
{
    border-right: 4px solid;
    border-color:  #0A141B;
}

.imgzone
{
outline-style: solid;
        outline-width: 4px;
        outline-color: #0A141B;
}
</style>
<div class="jumbotron" style="color:#fa9632">

<div class="wrapper">
    <div class="leftpane">
        <img class="imgleft" alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpath?>" width="200" height="200">
    </div>
        
    <div class="rightpane">
         <h4 class="textcolor"  style="text-align: center;">
             Creado por: <em></em>
         </h4> 
        <h4 style="border-bottom: 4px solid; border-color: #0A141B;"></h4>
        
        <h4 class="textcolor">
            Fuerte Contra/En:
            <img alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpathClassfuerte?>" width="25" height="25"> 
            <img alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpathElementfuerte?>" width="20" height="20"> 
            <img class="imgzone" alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpathZona?>" width="120" height="40"> 
        </h4>
        
        <h4 class="textcolor">
            &nbsp;&nbsp;Débil Contra/En:
            <img alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpathClassdebil?>" width="25" height="25"> 
            <img alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpathElementdebil?>" width="20" height="20"> 
            <img class="imgzone" alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpathZonadebil?>" width="120" height="40"> 
        </h4>
    </div>
    
    <div class="middlepane">
        <h3></h3>
        <h4 class="textcolor">Nivel: <em><?= $mymodel->nivel?></em></h4> 
        <h4 class="textcolor">Clase: <em><?=  $mymodel->clase?></em></h4>
        <h4 class="textcolor">
            Tipo:
            <img alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpathClass?>" width="25" height="25"> 
            Elemento:
            <img alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpathElement?>" width="20" height="20"> 
        </h4>
        <h4 class="textcolor"">Zona Favorita:</h4>
        <img class="imgzone" alt="Qries" src="<?php echo Yii::$app->request->baseUrl.$imgpathZona?>" width="120" height="40"> 
    </div>
    
    <div class="leftpanebottom">
        <h4 class="textcolorG">Victorias: <em> <?= $victories ?></em></h4> 
        <h4 class="textcolorR">Derrotas: <em> <?= $defeats ?></em></h4>
        <h4 class="textcolor">Matanzas: <em><?= $kills ?></em></h4>
        <h4 class="textcolor">Winrate: <em><?= $winrate ?>%</em></h4>
        <h4></h4>
    </div>
    
    <div class="rightpanebottom">
        <p class="textcolor">Historial de tus luchas</p>
        <div>
            <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_estadisticas',
                'viewParams' => ['imgpath' => $imgpath, 
                                 'imgpathClass' => $imgpathClass, 
                                 'imgpathElement' => $imgpathElement,
                                 'imgpathZona' => $imgpathZona],

                'layout' => "{pager}\n{items}",
            ]);
            ?>
        </div>
    </div>
    
    <div class="leftpanebottomextra">
        <h5 class="textcolor">Victima: <em><?= $victima?></em></h5> 
        <h5 class="textcolor">Némesis: <em><?= $nemesis?></em></h5>
    </div>
    
</div>
    <p></p>
        <?= Html::a('Volver', ['/personajes/personajes'], ['class'=>'btn btn-warning']) ?>
    

</div>

views/personajes/resultadocombate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\widgets\ListView;

use app\models\Clases;
use app\models\Zonas;
use app\models\Elementos;

use app\controllers\ClasesController;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//RESULTADO DEL COMBATE

$url = Yii::getAlias("@web") . '/imgs/others/';  
?>

<style>
body {
    background:url(<?= $url ?>bg1.png);
    background-attachment: fixed;
    background-size: cover;
        font-family: 'teen', serif;
}

.title {
  color:#fa9632;
  text-align: center;
}

.text {
  color:#fff3b8;
  text-align: center;
}

.imageborder
{
    border: 4px solid;
    border-color:  #0A141B;
  display: block;
  margin-left: auto;
  margin-right: auto;
}

.block
{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
</style>

<h1 class="title"><?php echo $resultado ?></h1>
<img class="imageborder" src="<?php echo Yii::$app->request->baseUrl.$imgclase?>" width="200" height="200">
<h1 class="text"><?php echo $destinoniveles ?></h1>
<h1 class="text"><?php echo $destinojugador ?></h1>

<div style="display: flex; align-items: center; justify-content: center;">
    <p><?= Html::a('Luchar otra vez!', ['/personajes/enfrentamiento', 'id' => $model1->cod], ['class'=>'btn btn-warning']) ?> </p>

</div>
<div style="display: flex; align-items: center; justify-content: center;">
    <p><?= Html::a('Volver', ['/personajes/personajes'], ['class'=>'btn btn-warning']) ?> </p>
</div>

views/personajes/resultadocombatelose.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\widgets\ListView;

use app\models\Clases;
use app\models\Zonas;
use app\models\Elementos;

use app\controllers\ClasesController;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//RESULTADO DEL COMBATE SI MUERES! PARA QUE NO PUEDAS VOLVER A LUCHAR SI ESTAS MUERTO
$url = Yii::getAlias("@web") . '/imgs/others/';  
?>

<style>
body {
    background:url(<?= $url ?>bg1.png);
    background-attachment: fixed;
    background-size: cover;
        font-family: 'teen', serif;
}

.title {
  color:#fa9632;
  text-align: center;
}

.text {
  color:#fff3b8;
  text-align: center;
}

.imageborder
{
    border: 4px solid;
    border-color:  #0A141B;
  display: block;
  margin-left: auto;
  margin-right: auto;
}

.block
{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
</style>

<h1 class="title"><?php echo $resultado ?></h1>
<img class="imageborder" src="<?php echo Yii::$app->request->baseUrl.$imgclase?>" width="200" height="200">
<h1 class="text"><?php echo $destinoniveles ?></h1>
<h1 class="text"><?php echo $destinojugador ?></h1>

<div style="display: flex; align-items: center; justify-content: center;">
    <p><?= Html::a('Volver', ['/personajes/personajes'], ['class'=>'btn btn-warning']) ?> </p>
</div>